.PHONY: bezier

bezier: main.o ErrorChecker.o Vec2D.o
	g++-12 main.o Vec2D.o ErrorChecker.o -lSDL2 -o bezier

main.o: main.cpp
	g++-12 --std=c++23 -c -I/usr/include/SDL2 main.cpp

ErrorChecker.o: ./utils/ErrorChecker.cpp
	g++-12 --std=c++23 -c -I/usr/include/SDL2 ./utils/ErrorChecker.cpp

Vec2D.o: ./utils/Vec2D.cpp
	g++-12 --std=c++23 -c -I/usr/include/SDL2 ./utils/Vec2D.cpp

